baseurl = "https://example.com"
title = "Don J. Kahn"
theme = "dimension"
languageCode = "en-us"
defaultContentLanguage = "en"
enableRobotsTXT = true
disableKinds=["RSS"]

[params]
  description = '<!--[-->Practicing Continuous Improvement<!--]--><br />'
  # logoimage= "/images/dj.jpg"
  logo = "fa-bicycle"
  # logo = "fa-empire"
  # copyright = "Untitled"

[[params.social]]
medium = "linkedin"
icon = "linkedin"
link = "https://linkedin.com/in/kahdojay"

[[params.social]]
  medium = "twitter"
  icon = "twitter"
  link = "https://twitter.com/kahdojay"

[[params.social]]
  medium = "medium"
  icon = "medium"
  link = "https://medium.com/@kahdojay"

[[params.social]]
  medium = "github"
  icon = "github"
  link = "https://github.com/kahdojay"

[[params.social]]
  medium = "instagram"
  icon = "instagram"
  link = "https://www.instagram.com/kahdojay/"

[blackfriday]
  plainIDAnchors = true
  hrefTargetBlank = true
